apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildkite-deployment-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: buildkite
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

