steps:
  - label: "👷‍♂️ Build"
    command: echo "Build the rocket"
    key: build

  - label: "✅ Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: "🚀 Deploy-Test"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":kubernetes: Install kubectl & gcloud"
    command: |
      echo "🔧 Installing kubectl..."
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      mv kubectl /usr/local/bin/
      kubectl version --client
    key: configure
    depends_on: deploy

  - label: ":rocket: Deploy"
    command:
      - "cd src"                            
      - "docker build -t us-central1-docker.pkg.dev/arun-poc/buildkite/buildkite-app:latest ." 
      - "docker push us-central1-docker.pkg.dev/arun-poc/buildkite/buildkite-app:latest"        
      - "kubectl apply -f final.yaml"              
    key: finaldeploy
    depends_on: configure

# steps:
#   - label: "👷‍♂️ Build"
#     command: echo "Build the rocket"
#     key: build

#   - label: "✅ Test"
#     command: echo "Test the rocket"
#     key: test
#     depends_on: build

#   - label: "🚀 Deploy-Test"
#     command: echo "Launch the rocket"
#     key: deploy
#     depends_on: test

#   - label: ":kubernetes: Install kubectl & gcloud"
#     command: |
#       echo "🔧 Installing kubectl..."
#       curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#       chmod +x kubectl
#       mv kubectl /usr/local/bin/
#       kubectl version --client
#     key: configure
#     depends_on: deploy

#  - label: ":rocket: Deploy"
#     command: 
#       - "cd src"                            
#       - "docker build -t us-central1-docker.pkg.dev/arun-poc/buildkite/buildkite-app:latest ." 
#       - "docker push us-central1-docker.pkg.dev/arun-poc/buildkite/buildkite-app:latest"        
#       - "kubectl apply -f final.yaml"              
#     key: finaldeploy
#     depends_on: configure