steps:
  - label: "👷‍♂️ Build"
    command: echo "Build the rocket"
    key: build

  - label: "✅ Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: "🚀 Deploy-Test"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":kubernetes: Deploy"
    command: sudo apt update && sudo apt install -y gettext

  - label: ":rocket: Push to :kubernetes:"
    command: script/buildkite/deploy
    concurrency: 1
    concurrency_group: deploy/tutorial