steps:
  - label: "👷‍♂️ Build"
    command: echo "Build the rocket"
    key: build

  - label: "✅ Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: "🚀 Deploy-Test"
    command: echo "Launch the rocket"
    key: deploy
    depends_on: test

  - label: ":kubernetes: Install kubectl"
    command: |
      echo "🔧 Installing kubectl..."
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      mv kubectl /usr/local/bin/
      kubectl version --client
    key: configure
    depends_on: deploy

  - label: ":rocket: Push to :kubernetes:"
    command: script/buildkite/deploy
    concurrency: 1
    concurrency_group: deploy/tutorial
    key: finaldeploy
    depends_on: configure             